version: '3'
services:
    nginx:
         build: .docker/nginx
         ports:
             - '80:80'
         links:
             - php
         volumes:
             - ./logs/nginx/:/var/log/nginx:cached

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4

    php:
           build: .docker/php-fpm
           ports:
               - '9002:9000'
           volumes:
               - ./symfony/:/var/www/symfony
           links:
               - mysql
           environment:
             - maildev_host=sf4_maildev
           depends_on:
             - maildev
             - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 8001:80
